### PR TITLE
[#101] Stream Listing Page

### LINKED ISSUE #101: Stream listing page

### LINKED ISSUE #106: Table header for device lists not sticking
**Operating system:** 
 
 
* Windows 10
* Google Chrome version 86.0.4240.111

**Steps to reproduce:**

1. Run the frontend (npm start)
2. Wait for the table to populate enough devices that scrolling is necessary.
3. Scroll down in the table.
* If the table doesn't have enough devices, try expanding the extra information sections to add to the height. 

**Expected result:**

* Header cells (with search boxes) should stick to the top and remain visible as you scroll down.

**Actual result:**
 
* Header cells do not stick and instead disappear as you scroll down.

**Visual proof:**
 
|  Actual  |
|:---------------:|
| 
image |

| Expected |
|:---------------:|
| 
image |

### PR DESCRIPTION
**Pull request by gdzooks**
# General info

**Issue number**: #101 

**Task description**: 
 - Created "Current Streams" page/fragment
 - List of streams is hooked up to backend and updates as necessary
 - Closes #106 
 
**Additional Changes**:
- Small refactoring activities happened in here.

| Original | Original but I updated it in this PR | 
|:---------------:|:-------------:|
| image | image|

# Testing

**Test coverage**:
* yes
* 86.6% (trying for more but don't get your hopes up)

# Additional notes

**Note to reviewers**:
* N/A for the moment

**To do before merging**:
- [x] Waiting for #122 and #124 to be merged
- [x] Possible large-ish refactor incoming as a result of the above
- [x] Update testing

### CODE REVIEW

File: frontend/src/streamlist/HeadCells.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+            new HeadCell("timeelapsed", "Time Elapsed", true, true),
+        ];
+    }
+
+    render() {
+        return (
+            <React.Fragment>
+                {this.headcells.map((headCell) =>(
+                    <TableCell
+                        class="tableHeadCell lightestGrey"
```
Comment (jun-loke) [inline frontend/src/streamlist/HeadCells.js]: Use className to make it sticky

File: frontend/src/streamlist/StreamsTable.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        return (
+            <React.Fragment>
+                <Box>
+                <TableContainer style={{ maxHeight: 450 }}>
+                    <Table stickyHeader aria-label="sticky table">
+                        <TableHead>
+                            <TableRow>
+                                <TableCell class="tableHeadCell lightestGrey" style={{ width: 1, padding: 0, paddingLeft: 5 }}></TableCell>
+                                <HeadCells />
+                                <TableCell class="tableHeadCell lightestGrey" align="center">
```
Comment (jun-loke) [inline frontend/src/streamlist/StreamsTable.js]: Use className to make it sticky

**Review by jun-loke — DISMISSED** [review]
Preliminary pass. Looks good overall just a small change to make in order to keep it sticky
(I also recommend increasing your data list in order to verify sticky, but that's not very important)

**Comment by felixlapierre** [comment]
i am loving the code coverage we're getting on our prs! will do a thorough review in the morning

File: frontend/src/streamlist/HeadCells.js (hunk 1 above)
Comment (gdzooks) [reply frontend/src/streamlist/HeadCells.js]: 👍

File: frontend/src/streamlist/StreamsTable.js (hunk 2 above)
Comment (gdzooks) [reply frontend/src/streamlist/StreamsTable.js]: 👍

File: frontend/src/model/StreamInfo.js [hunk 3]
```diff
@@ -0,0 +1,12 @@
+export default class StreamInfo {
+    constructor(id, date, sender, receiver, status, type, time, extras) {
+        this.id = id;
+        this.date = date;
+        this.sender = sender;
+        this.receiver = receiver;
+        this.status = status;
+        this.type = type;
+        this.time = time;
+        this.extras = extras;
```
Comment (felixlapierre) [inline frontend/src/model/StreamInfo.js]: In the backend we aren't tracking date, status, type or time, so we'll have to make an issue to add that to the backend & put static values for now...

File: frontend/src/api/DeviceApi.js [hunk 4]
```diff
@@ -23,6 +24,16 @@ export function getReceivers(callback) {
...
+
+export function getStreams(callback) {
+    axios("http://localhost:8080/decoder")
+        .then((streams) => {
+            // empty for now
+        })
+        .catch((error) => {
+            SampleData.getStreams(callback);
         });
 }
```
Comment (felixlapierre) [inline frontend/src/api/DeviceApi.js]: We should move this to a StreamApi.js file

File: frontend/src/streamlist/HeadCells.js [hunk 5]
```diff
@@ -0,0 +1,45 @@
+import React from 'react'
+import {
+    TableCell,
+    TableSortLabel,
+    Typography,
+} from "@material-ui/core"
+import HeadCell from '../model/HeadCell'
+
+export default class StreamListHeadCells extends React.Component {
```
Comment (felixlapierre) [inline frontend/src/streamlist/HeadCells.js]: Class name should match file name, or it'll get reported as a smell by sonarqube

**Review by felixlapierre — COMMENTED** [review]
Couple of lil comments

File: frontend/src/model/StreamInfo.js (hunk 3 above)
Comment (gdzooks) [reply frontend/src/model/StreamInfo.js]: ~~second constructor with the static values as a temporary fix?~~ 
nevermind 2nd constructor doesn't work lol i'll just change the constructor to only take id, sender, receiver, and extras and update the sample data for the moment.

File: frontend/src/api/DeviceApi.js (hunk 4 above)
Comment (gdzooks) [reply frontend/src/api/DeviceApi.js]: i'll keep that in mind for once #124 is merged :+1:

File: frontend/src/DefaultMakeStylesTheme.js [hunk 6]
```diff
@@ -0,0 +1,14 @@
+import { makeStyles } from "@material-ui/core";
+
+export default function useStyles() {
```
Comment (gdzooks) [inline frontend/src/DefaultMakeStylesTheme.js]: this gives a code smell because the function name doesn't match the file name, but i'm happy with how descriptive the file name is.
should i just change the function name and make sure we use `import * as useStyles`?

File: frontend/src/api/DeviceApi.js (hunk 4 above)
Comment (gdzooks) [reply frontend/src/api/DeviceApi.js]: addressed in: 7c06db3 ~

**Comment by felixlapierre** [comment]
Sharon and I will be reviewing

File: frontend/src/createStream/StreamingPage.js [hunk 7]
```diff
@@ -24,10 +24,12 @@ export default class StreamingPage extends React.Component {
...
                     </Box>
                     <div id="StreamingTable">
-
                         <StreamingTable dataSource={this.props.dataSource} />
                     </div>
-                </Box>                
+                </Box>
+                <Box>
+                    <StreamList dataSource={this.props.streamSource} />
+                </Box>
```
Comment (felixlapierre) [inline frontend/src/createStream/StreamingPage.js]: So this component takes two props
- dataSource which gets passed to StreamingTable.dataSource
- streamSource which gets passed to StreamList.dataSource

Maybe we can rename the `dataSource` prop on `StreamingPage` to `deviceSource` instead to reflect what it's used for? Otherwise it's kind of confusing, since streamSource is also a data source in a way.

File: frontend/src/devicelist/HeadCells.js [hunk 8]
```diff
@@ -38,11 +38,11 @@ export default class HeadCells extends React.Component {
         return (
             <React.Fragment>
 
-                <TableCell class="tableHeadCell lightestGrey" style={{ width: 1, padding: 0, paddingLeft: 5 }}></TableCell>
+                <TableCell className="tableHeadCell lightestGrey" style={{ width: 1, padding: 0, paddingLeft: 5 }}></TableCell>
```
Comment (felixlapierre) [inline frontend/src/devicelist/HeadCells.js:41]: thank youuu 👍

File: frontend/src/api/__tests__/StreamApi.test.js [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+        it('should call axios.get and return an array of streams', () => {
+            axios.get.mockResolvedValue(mockStreams);
+
+            StreamApi.getAllStreams();
+
+            expect(axios.get).toHaveBeenCalledWith("http://localhost:8080/stream");
+        })
+        it('should use sample data in the case of an error', () => {
+
+        })
```
Comment (felixlapierre) [inline frontend/src/api/__tests__/StreamApi.test.js]: Missing test? Or are we filling it in later?

File: frontend/src/api/__tests__/StreamApi.test.js [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+
+    afterEach(() => {
+        jest.clearAllMocks();
+    })
+
+    describe('getStream', () => {
+        it('should call axios.get and return a single stream\'s information', () => {
+            StreamApi.getStream(123);
+            
+            expect(axios.get).toHaveBeenCalledWith(`http://localhost:8080/stream/123`);
```
Comment (felixlapierre) [inline frontend/src/api/__tests__/StreamApi.test.js]: Are we checking that the callback is being invoked with the right value?

File: frontend/src/model/ConvertDataFormat.js [hunk 11]
```diff
@@ -0,0 +1,43 @@
...
+            ["Additional Device Info goes here."])
+    );
+}
+
+export function convertToAxios(deviceInfo) {
+    if (deviceInfo.hasOwnProperty("outputs")) {
+        return {
+            "serialNumber": deviceInfo.serialNumber,
+            "lastCommunication": deviceInfo.lastCommunication,
+            "device": {
```
Comment (felixlapierre) [inline frontend/src/model/ConvertDataFormat.js]: I'm fine with separating the data formats. but i think we can maybe use different names. 
For the local data formats i'm not sure of what the name could be. Maybe "view". Or just "convertToDataObject"
For the format the server uses i would call it "convertToServiceObject" or something. Calling it "axios" is misleading imo.
But i'm not set on any of those names and i don't particularly like any of them...

**Review by felixlapierre — DISMISSED** [review]
LGTM, minor comments. hopefully we can make the data representation consistent in the backend and frontend soon though.

File: frontend/src/createStream/StreamingPage.js (hunk 7 above)
Comment (sharon-ho) [reply frontend/src/createStream/StreamingPage.js]: I also agree with what Felix said and I think renaming the props will be clearer.

File: frontend/src/devicelist/DeviceListPage.js [hunk 12]
```diff
@@ -1,37 +1,26 @@
...
 } from "@material-ui/core"
 
 import TitleBox from './TitleBox'
 import ContentsTable from './ContentsTable'
 import DynamicBreadcrumb from '../General/DynamicBreadcrumb';
+import * as useStyles from '../DefaultMakeStylesTheme';
 
 export default class DeviceListPage extends React.Component {
     constructor(props) {
         super(props);
```
Comment (sharon-ho) [inline frontend/src/devicelist/DeviceListPage.js]: Useless constructor, can be removed.

File: frontend/src/index.js [hunk 13]
```diff
@@ -26,7 +26,7 @@ ReactDOM.render(
         )} />
         <Route exact path="/Streaming" 
         render={(props) => (
-            <StreamingTablePage {...props} dataSource={DeviceApi} />
+            <StreamingTablePage {...props} dataSource={DeviceApi} streamSource={StreamApi} />
         )}  />
```
Comment (sharon-ho) [inline frontend/src/index.js]: Currently nothing gets rendered on my end besides the breadcrumbs? Should the page currently route to the `My Devices` page?

image

File: frontend/src/StatusIndicator.js [hunk 14]
```diff
@@ -1,6 +1,5 @@
 import React from 'react';
 
-
 export default class StatusIndicator extends React.Component {
 
     constructor(props) {
```
Comment (sharon-ho) [inline frontend/src/StatusIndicator.js]: Useless constructor, can be removed.

**Review by sharon-ho — CHANGES_REQUESTED** [review]
Just some minor changes. There is one small thing I noticed while reviewing this PR that I think we should make an issue for. Because there is a delay when fetching data that's to be displayed and for them to render on the page, there should be some kind of loading animation/page that displays during those couple of seconds that's happening. This is so that the user is not left hanging with empty elements on the page, which can interfere with the user experience.

I'm familiar with how to implement a solution for that, so that shouldn't be much of an issue.

Overall good job!

File: frontend/src/index.js (hunk 13 above)
Comment (jun-loke) [reply frontend/src/index.js]: that's because you're at the homepage, if you click on Streaming, you'll be brought the streaming page where you can see Kouki's work. This was a decision I made in my pr because we do have 2 pages atm

Comment (sharon-ho) [reply frontend/src/index.js]: I imagined that was the case, however in that case the breadcrumbs are misleading and should be removed.

Comment (jun-loke) [reply frontend/src/index.js]: But then there's no immediate way to navigate to the different pages, without adding a new button or typing it in.

Comment (sharon-ho) [reply frontend/src/index.js]: I see your point. I think having buttons or typing them in makes more sense, but then again that's subject to debate. Since this page will be revamped in the future, I guess it's alright for it to stay as is, especially since it's not in the scope of this PR.

**Review by ButlerJAL — DISMISSED** [review]
My review brings no additional feedback to what has already been said.

The empty test found by @felixlapierre is odd, but like him I am fine with approving as-is. My assumption is that it's there as a reminder to be written or worst case cleaned up in a future PR.

@sharon-ho has brought up issues of useless constructors, but seeing that those were not introduced by your changes, I am still inclined to approve this PR as to not keep this PR stale.

I have a task dedicated to improve our code quality, so, I'll keep the unresolved comments written on this PR in mind to fix.

**Review by sharon-ho — DISMISSED** [review]
I've realized that I requested changes, but after some discussion and thinking over, I am changing it to an approval. As @MrJCipherButtles mentioned, the useless constructors were not introduced in the new code changes, therefore are not in the scope of this PR. After discussing with @arejayelle, the landing page will be kept as is while there's no clear idea yet what it should display for now.

File: frontend/src/api/__tests__/StreamApi.test.js (hunk 9 above)
Comment (gdzooks) [reply frontend/src/api/__tests__/StreamApi.test.js]: ~hoping to fill it in later. would you rather it be done for this PR?~
added a `TODO` comment for now

File: frontend/src/api/__tests__/StreamApi.test.js (hunk 10 above)
Comment (gdzooks) [reply frontend/src/api/__tests__/StreamApi.test.js]: ~yep, want me to add a comment to explain just in case?~
nevermind - if i had to ask then better safe than sorry :joy:

File: frontend/src/index.js (hunk 13 above)
Comment (gdzooks) [reply frontend/src/index.js]: @sharon-ho currently all page navigation is very.. let's say patchworked? i'm assuming we're going to have a big refactoring task in the future to handle it :joy: (revisions for workflows are coming up i believe?)

File: frontend/src/createStream/StreamingPage.js (hunk 7 above)
Comment (gdzooks) [reply frontend/src/createStream/StreamingPage.js]: what do you guys think about renaming the prop for device list to `deviceSource` as well, for consistency?

File: frontend/src/model/ConvertDataFormat.js (hunk 11 above)
Comment (gdzooks) [reply frontend/src/model/ConvertDataFormat.js]: hmm i'll change them to `DataObject` and `ServiceObject` for now and in the future we can make a bug/refactoring issue for another change if we feel it's necessary.

**Comment by gdzooks** [comment]
all comments read an commits made to address some of them so please re-review~ @felixlapierre @sharon-ho @MrJCipherButtles

**Comment by gdzooks** [comment]
comments read and some of them addressed! ~(ignore my mess of new commits where i try to fix the build because i missed a bunch of refactors in the tests lol)~
ready for re-review :joy: @sharon-ho @felixlapierre @MrJCipherButtles

File: frontend/src/createStream/StreamingPage.js (hunk 7 above)
Comment (felixlapierre) [reply frontend/src/createStream/StreamingPage.js]: Maybe `deviceDataSource` and `streamDataSource`?

File: frontend/src/api/__tests__/StreamApi.test.js (hunk 10 above)
Comment (felixlapierre) [reply frontend/src/api/__tests__/StreamApi.test.js]: Sorry i realize i misunderstood
StreamApi returns a promise, we should use an assertion to verify that the promise resolves to the correct value.
You may have to write an asynchronous test, not sure how Jest handles that.

File: frontend/src/index.js (hunk 13 above)
Comment (felixlapierre) [reply frontend/src/index.js]: I think we can leave this as is, it's a temporary replacement for a homepage that we'll have to make in a later PR.

**Review by felixlapierre — DISMISSED** [review]
LGTM!

**Review by felixlapierre — APPROVED** [review]

**Review by ButlerJAL — APPROVED** [review]
