### PR TITLE
Removed CascadeType.MERGE from channel entities

### LINKED ISSUE #242: Error when when getting decoder/encoder streams: Multiple representations of the same entity are being merged
**Operating system:**
Should happen on all OS, confirmed on Linux and Windows

**Steps to reproduce:**

- Invoke the GET request of 'getEncoderStreams' or 'getDecoderStreams' endpoints

**Expected result:**

- Streams is returned in a  list form 

**Actual result:**

### PR DESCRIPTION
**Pull request by felixlapierre**
# General info

**Issue number**:  #242
**Task description**: 

 - Fix an issue where getting the streams of a device fails.
 
 

**Original** 
image

**Updated**
image

# Testing

**Test coverage**:
N/A, this could really use an integration test but right now i'm creating this PR as a hotfix to help maxim with #195

# Additional notes

**Note to reviewers**:
Unsure what the impact of removing CascadeType.MERGE is, it doesn't seem to break anything but if someone who has more knowledge than me could confirm that would be awesome.

### CODE REVIEW

**Comment by mohhef** [comment]
This is most probably going to to crash 'createInputChannel' & 'createOutputChannel'

**Comment by felixlapierre** [comment]
Update: I manually tested creating an input channel in postman and it did not crash. I also tested device registration and i can register encoders and decoders just fine.

File: src/main/java/org/beanpod/switchboard/entity/InputChannelEntity.java [hunk 1]
```diff
@@ -34,9 +34,7 @@
   @JoinColumn(name = "channel_id")
   private ChannelEntity channel;
 
-  @ManyToOne(
-      fetch = FetchType.LAZY,
-      cascade = {CascadeType.MERGE})
+  @ManyToOne(fetch = FetchType.LAZY)
```
Comment (FGRCL) [inline src/main/java/org/beanpod/switchboard/entity/InputChannelEntity.java:37]: This fix sorta makes sense to me when I look at [the documentation for `CascadeType.Merge`](https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#pc-cascade-merge). We were trying to get the `InputChannelEntity`, then because its `DecoderEntity` has a `CascadeType.Merge` it would try to add that Decoder to its select. Then, because `input` in `DecoderEntity` has a `CascadeType.All` it would try to reselect the `InputChannelEntity`. At least, that's what I understood from it.

**Review by FGRCL — APPROVED** [review]

**Review by mohhef — APPROVED** [review]
I have tested the main Endpoints being utilized, this fix seems to work!
