### PR TITLE
[#6/14/15/21] Endpoints for receiver and sender

### LINKED ISSUE #6: Service: Endpoint for getting a list of senders

### LINKED ISSUE #14: Service: Endpoint for registering a sender
Also includes setting up the database (mysql, jdbc or hibernate, etc)

### LINKED ISSUE #15: Service: Endpoint for registering a receiver

### LINKED ISSUE #21: Service: Endpoint for getting a list of receivers

### LINKED ISSUE #22: Service: Endpoints for getting one sender/receiver

### LINKED ISSUE #61: Post request to/encoder results in an internal server error
**OS:** Windows 10

**Steps to reproduce:** 

Make a post request to /encoder using the following body:
{
    "serialNumber": 2
}

**Expected result:**

The body should be populated in the database and the server should return a successful response.

**Actual result:**

Return of an internal server error.

**Visual proof:**

### PR DESCRIPTION
**Pull request by mohhef**
# General info
Connection to MySQL: URL/password/username are included in system.properties
Use postman to test post and get requests

**Issue number**:  6/14/15/21

**Task description**: 

- Establish database connection to MySQL
- Map entities to the database
- Create post and get methods for device/decoder/encoder(retrieveAllX, retrieveX, createX)

**Note to reviewers**:
This pull request does not directly implement the API spec because of structural changes, API spec to be implemented
Component tests to be added to the HTTP requests

Reasons for having endpoints for Device:
- To create a device without getting assigned to either an encoder or a decoder
- To deassign a device from an encoder then reassign it to a decoder without deleting all its attributes and visa versa
- To query getting all the devices without queries 2 individual tables

Access api used by the appliction(not yaml): http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
The swagger-ui should match the yaml when openApi is implemented properly, however you can still use swagger-ui endpoint for testing purposes

### CODE REVIEW

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    @Autowired
+    DeviceDaoImpl service;
+
+    @GetMapping("/device")
+    public List<Device> retrieveAllDevices(){
+        return service.getDevices();
+    }
+
+    @GetMapping("/device/{serialNumber}")
+    public EntityModel<Device> retrieveDevice(@PathVariable long serialNumber){
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java]: As misleading as it is, serial numbers can contain letters, so we have to store them as strings :/

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+import java.util.Optional;
+
+@RestController
+public class EncoderController {
+
+    private Logger logger = LoggerFactory.getLogger(this.getClass());
+
+    @Autowired
+    EncoderDaoImpl encoderService;
+//
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: Remove comment

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    public List<Encoder> retrieveAllEncoders(){
+        return encoderService.getEncoders();
+    }
+
+    @PostMapping("/encoder")
+    public ResponseEntity createEncoder(@RequestBody Encoder encoder){
+        Optional<Device> deviceOptional = deviceService.findDevice(encoder.getSerialNumber());
+        encoder.setDevice(deviceOptional.get());
+
+        //  encoderRepository.saveAndFlush(encoder);
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: Remove commented code

File: service/switchboardapp/src/main/java/com/switchboard/app/dao/DecoderDao.java [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+import com.switchboard.app.domain.Device;
+import com.switchboard.app.domain.Encoder;
+import org.springframework.stereotype.Repository;
+
+import java.util.List;
+import java.util.Optional;
+
+public interface DecoderDao {
+
+//    Decoder addDao(Decoder decoder);
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/dao/DecoderDao.java]: Remove commented code

File: service/switchboardapp/src/main/resources/application.properties [hunk 5]
```diff
@@ -1 +1,11 @@
+spring.h2.console.enabled=true
+spring.jpa.hibernate.ddl-auto=update
 
+#spring.datasource.url=jdbc:h2:mem:testdb
+#spring.jpa.show-sql=true
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/resources/application.properties]: Commented properties, do we need to keep them for easily enabling stuff in the future?

File: service/switchboardapp/src/main/resources/data.sql [hunk 6]
```diff
@@ -0,0 +1,4 @@
+insert into device(serial_number, display_name, Status) values (1,'Device1','Running');
+insert into device(serial_number, display_name, Status) values (2,'Device2','Running');
+
+insert into encoder(serial_number) values(1);
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/resources/data.sql]: Is this just default data to insert into the database?

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/CustomRestExceptionHandler.java [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;
+
+@ControllerAdvice
+@RestController
+public class CustomRestExceptionHandler extends ResponseEntityExceptionHandler {
+
+    @ExceptionHandler(Exception.class)
+    public final ResponseEntity<Object> handleAllExceptions(Exception ex, WebRequest request){
+
+       ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.INTERNAL_SERVER_ERROR, ex.getMessage(), "error occured");
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/exceptions/CustomRestExceptionHandler.java]: Change message to "An unknown error occurred"

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+    @Column(name = "display_name")
+    private String DisplayName;
+
+    private String Status;
+
+    @OneToOne(mappedBy = "device")
+    private Encoder encoder;
+
+    @OneToOne(mappedBy = "device", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
+    private Decoder decoder;
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java]: Why does Encoder not have CascadeType.ALL and FetchType.LAZY?

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
+import lombok.Getter;
+import lombok.NoArgsConstructor;
+import lombok.Setter;
+
+import javax.persistence.*;
+
+@Entity
+@AllArgsConstructor
+@NoArgsConstructor
+@Setter@Getter
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: I suggest replacing @Setter and @Getter with @Data, it will include those two annotations plus ToString, HashCode, and RequiredArgsConstructor

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+    @Autowired
+    DecoderDaoImpl decoderService;
+
+    @Autowired
+    DeviceDaoImpl deviceService;
+
+    @GetMapping("/decoder")
+    public List<Decoder> retrieveAllDecoders(){
+        return decoderService.getDecoders();
+    }
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java]: I see that we support retrieving a specific device (which includes its encoder and decoder info) but should we support retrieving a specific encoder or decoder too?

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java [hunk 11]
```diff
@@ -0,0 +1,27 @@
...
+@JsonIgnoreProperties({"hibernateLazyIntializer","handler","device"})
+
+public class Decoder {
+
+    @Id
+    @Column(name = "serial_number")
+    private Long serialNumber;
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: Add @NotNull unless that's already validated through the other annotations. If you do, add @Valid to the create new decoder endpoint.

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java [hunk 12]
```diff
@@ -0,0 +1,30 @@
...
+@ToString
+@JsonIgnoreProperties({"hibernateLazyIntializer","handler","encoder","decoder"})
+public class Device {
+
+    @Id
+    @Column(name = "serial_number")
+    private Long serialNumber;
+
+    @Column(name = "display_name")
+    private String DisplayName;
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java]: Add @NotNull to serial number and display name

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Encoder.java [hunk 13]
```diff
@@ -0,0 +1,24 @@
...
+@AllArgsConstructor
+@NoArgsConstructor
+@Getter@Setter
+@JsonIgnoreProperties({"hibernateLazyIntializer","handler","device"})
+@ToString
+public class Encoder {
+
+    @Id
+    @Column(name = "serial_number")
+    private Long serialNumber;
```
Comment (felixlapierre) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Encoder.java]: Add @NotNull unless that's already validated by the other annotations. If you do, add @Valid to the create encoder endpoint Encoder argument.

**Review by felixlapierre — CHANGES_REQUESTED** [review]
Looking good!! Have some minor suggestions + feedback, and one major change: we have to change Serial Number to a string instead of a long since it can contain letters (confusing, i know)

File: service/switchboardapp/contracts/api-spec.yaml [hunk 14]
```diff
@@ -11,7 +11,7 @@ servers:
 paths:
   /Encoders:
     get:
-      operationId: getEncoders
+      operationId: retrieveAllEncoders
```
Comment (FGRCL) [inline service/switchboardapp/contracts/api-spec.yaml:46]: Why did we change this name?

File: service/switchboardapp/pom.xml [hunk 15]
```diff
@@ -40,13 +40,26 @@
 			<scope>runtime</scope>
 			<optional>true</optional>
 		</dependency>
-
+		<!-- https://mvnrepository.com/artifact/com.h2database/h2 -->
```
Comment (FGRCL) [inline service/switchboardapp/pom.xml]: I'm not sure what this comment is trying to specify

File: service/switchboardapp/pom.xml [hunk 16]
```diff
@@ -40,13 +40,26 @@
...
-
+		<dependency>
+			<groupId>mysql</groupId>
+			<artifactId>mysql-connector-java</artifactId>
+			<scope>runtime</scope>
+		</dependency>
+		<dependency>
+			<groupId>org.springframework.hateoas</groupId>
+			<artifactId>spring-hateoas</artifactId>
+			<version>1.1.2.RELEASE</version>
```
Comment (FGRCL) [inline service/switchboardapp/pom.xml]: let's define this versions in the <properties> section.

File: service/switchboardapp/pom.xml [hunk 17]
```diff
@@ -58,7 +71,10 @@
 				</exclusion>
 			</exclusions>
 		</dependency>
-
+        <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-data-jpa</artifactId>
+        </dependency>
```
Comment (FGRCL) [inline service/switchboardapp/pom.xml:86]: This dependency is not on the same indent level as the other dependencies.

File: service/switchboardapp/src/main/java/com/switchboard/app/SwitchboardApplication.java [hunk 18]
```diff
@@ -8,6 +8,7 @@
 
 	public static void main(String[] args) {
 		SpringApplication.run(SwitchboardApplication.class, args);
+
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/SwitchboardApplication.java]: I think we can remove this empty line.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java [hunk 19]
```diff
@@ -0,0 +1,48 @@
...
+import javax.validation.Valid;
+import java.net.URI;
+import java.util.List;
+import java.util.Optional;
+
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
+
+@RestController
+public class DecoderController {
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java:25]: This controller does not inherit the DecodersApi interface

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java [hunk 20]
```diff
@@ -0,0 +1,48 @@
...
+
+    @Autowired
+    DecoderDaoImpl decoderService;
+
+    @Autowired
+    DeviceDaoImpl deviceService;
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java:31]: I think we should define these as private final variables and use Lombok to generate the constructors. I think the dependencies will be easier to mock for unit testing that way. Lombok has a little bit of config that needs to be done with maven and Intellij, I've done it on my side so I can show you how to do it.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java [hunk 21]
```diff
@@ -0,0 +1,48 @@
...
+    public List<Decoder> retrieveAllDecoders(){
+        return decoderService.getDecoders();
+    }
+
+    @PostMapping("/decoder")
+    public ResponseEntity createDecoder(@RequestBody Decoder decoder){
+        Optional<Device> deviceOptional = deviceService.findDevice(decoder.getSerialNumber());
+        decoder.setDevice(deviceOptional.get());
+
+        Decoder savedDecoder = decoderService.addDecoder(decoder);
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java]: This logic seems like it belongs more in a repository or DAO

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java [hunk 22]
```diff
@@ -0,0 +1,48 @@
...
+        URI location = ServletUriComponentsBuilder.fromCurrentRequest().
+                path("/{serialNumber}").buildAndExpand(savedDecoder.getSerialNumber()).toUri();
+
+        return ResponseEntity.created(location).build();
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java:62]: For now, our api-specs only specify that we return a 200 when an object is successfully created.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java [hunk 23]
```diff
@@ -0,0 +1,62 @@
...
+import javax.validation.Valid;
+import java.net.URI;
+import java.util.List;
+import java.util.Optional;
+
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
+
+@RestController
+public class DeviceController implements DecodersApi {
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java]: Why are we adding this controller? the API never mentions a user facing Device model.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java [hunk 24]
```diff
@@ -0,0 +1,62 @@
...
+
+    @Autowired
+    DeviceDaoImpl service;
+
+    @GetMapping("/device")
+    public List<Device> retrieveAllDevices(){
+        return service.getDevices();
+    }
+
+    @GetMapping("/device/{serialNumber}")
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java]: Those mappings aren't part of our API specifications

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java [hunk 25]
```diff
@@ -0,0 +1,62 @@
...
+import java.util.Optional;
+
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
+import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
+
+@RestController
+public class DeviceController implements DecodersApi {
+
+    @Autowired
+    DeviceDaoImpl service;
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java:26]: Same comment about Lombok.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java [hunk 26]
```diff
@@ -0,0 +1,51 @@
...
+public class EncoderController {
+
+    private Logger logger = LoggerFactory.getLogger(this.getClass());
+
+    @Autowired
+    EncoderDaoImpl encoderService;
+//
+
+    @Autowired
+    DeviceDaoImpl deviceService;
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: Same comment about lombok.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java [hunk 27]
```diff
@@ -0,0 +1,51 @@
...
+import org.springframework.web.bind.annotation.*;
+import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
+
+import javax.validation.Valid;
+import java.net.URI;
+import java.util.List;
+import java.util.Optional;
+
+@RestController
+public class EncoderController {
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java:26]: This controller should inherit the EncoderApi interface.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java [hunk 28]
```diff
@@ -0,0 +1,51 @@
...
+
+    private Logger logger = LoggerFactory.getLogger(this.getClass());
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: Lombok has a @Slf4j defines this logger for you.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java (hunk 26 above)
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: same comment about lombok

File: service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java [hunk 29]
```diff
@@ -0,0 +1,29 @@
...
+    @Override
+    public Decoder addDecoder(Decoder decoder) {
+        return decoderRepository.save(decoder);
+    }
+
+    @Override
+    public List<Decoder> getDecoders() {
+        return decoderRepository.findAll();
+    }
+}
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java]: I believe repositories and DAO come from two different design patterns for the persistence layer. I'm going to suggest we move the methods of the DAOs to their corresponding repositories instead and get rid of the DAOs altogether.

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java [hunk 30]
```diff
@@ -0,0 +1,27 @@
...
+
+import javax.persistence.*;
+
+@Entity
+@AllArgsConstructor
+@NoArgsConstructor
+@Setter@Getter
+@JsonIgnoreProperties({"hibernateLazyIntializer","handler","device"})
+
+public class Decoder {
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: I think we should postfix our persistence layer objects with "Entities" to avoid confusion. I also intend on postfixing the API models with "Model".

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java (hunk 11 above)
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: Is it safe to use serial numbers as ID? From what I understood we could have multiple clients with the same serial number.

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceAlreadyExistsException.java [hunk 31]
```diff
@@ -0,0 +1,7 @@
+package com.switchboard.app.exceptions;
+
+public class DeviceAlreadyExistsException extends RuntimeException {
+    public DeviceAlreadyExistsException(String s) {
+        super(s);
+    }
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceAlreadyExistsException.java:6]: With Lombok I think we could get rid of the constructor with @RequiredArgsConstructor

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceNotFoundException.java [hunk 32]
```diff
@@ -0,0 +1,7 @@
+package com.switchboard.app.exceptions;
+
+public class DeviceNotFoundException extends RuntimeException {
+    public DeviceNotFoundException(String s) {
+        super(s);
+    }
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceNotFoundException.java:8]: Same comment about Lombok and the constructor

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java [hunk 33]
```diff
@@ -0,0 +1,25 @@
...
+@AllArgsConstructor
+@Getter
+public class ExceptionResponse {
+
+    public HttpStatus status;
+    public String message;
+    public List<String> errors;
+
+    public ExceptionResponse(HttpStatus status, String message, String error) {
+        super();
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java]: This class doesn't inherit anything. I think we can remove this super.

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java [hunk 34]
```diff
@@ -0,0 +1,25 @@
...
+        this.status = status;
+        this.message = message;
+        errors = Arrays.asList(error);
```
Comment (FGRCL) [inline service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java]: Th `Arrays.asList` doesn't seem to be doing much here. When applied on a string, `Arrays.asList` will return a list with a single element which is the string passed. We should change the `error` method parameter to either an array, a String or use varargs.

File: service/switchboardapp/src/main/resources/data.sql (hunk 6 above)
Comment (FGRCL) [reply service/switchboardapp/src/main/resources/data.sql]: Is this data added on boot? If that's the case we should make sure it's loaded only when the app is loaded with a test or debug profile.

**Review by FGRCL — CHANGES_REQUESTED** [review]

File: service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java (hunk 29 above)
Comment (FGRCL) [reply service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java]: I think the DAOs currently do the job of the service layer so we could rename them to that. In any case, the service layer should return their own data objects instead or the persistence layer's data objects.

**Comment by FGRCL** [comment]
Let's add #6  and #21 to this pull request

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java (hunk 1 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java (hunk 2 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: fixed

File: service/switchboardapp/src/main/resources/application.properties (hunk 5 above)
Comment (mohhef) [reply service/switchboardapp/src/main/resources/application.properties]: Ill keep the h2 property for now, in case anybody cant connect to sql they can test the application using h2.

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java (hunk 9 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: Good  idea

Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java (hunk 10 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java]: Yes. we did not do it in this pull request, we'll finish the rest of the concerns and get back to this one.

File: service/switchboardapp/src/main/resources/data.sql (hunk 6 above)
Comment (mohhef) [reply service/switchboardapp/src/main/resources/data.sql]: This data is loaded when using h2 in memory database. Ill make that clear!

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java (hunk 3 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/CustomRestExceptionHandler.java (hunk 7 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/exceptions/CustomRestExceptionHandler.java]: Fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java (hunk 11 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: I think @id will fail in the db level if the value is null, adding @NotNull is also a good idea to fail at the method validation level

Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java (hunk 12 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Encoder.java (hunk 13 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Encoder.java]: fixed

File: service/switchboardapp/pom.xml (hunk 15 above)
Comment (mohhef) [reply service/switchboardapp/pom.xml]: Removed.
Fixed.

File: service/switchboardapp/pom.xml (hunk 16 above)
Comment (mohhef) [reply service/switchboardapp/pom.xml]: Fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/SwitchboardApplication.java (hunk 18 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/SwitchboardApplication.java]: Fixed :)

File: service/switchboardapp/pom.xml (hunk 17 above)
Comment (mohhef) [reply service/switchboardapp/pom.xml:86]: On my local its fine but on GitHub you are right, whats causing that, do you have any idea?

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceAlreadyExistsException.java (hunk 31 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceAlreadyExistsException.java:6]: doesnt seem to work :/

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceNotFoundException.java (hunk 32 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/exceptions/DeviceNotFoundException.java:8]: doesnt seem to work :/

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java (hunk 34 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java]: Changed to string for now

File: service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java (hunk 33 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/exceptions/ExceptionResponse.java]: Yes, fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java (hunk 28 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/EncoderController.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/dao/DecoderDao.java (hunk 4 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/dao/DecoderDao.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java (hunk 29 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/dao/impl/DecoderDaoImpl.java]: My intention was that the repository will only contain custom queries that will not be mixed with JPA readily available operations. I however refactored the code, take a look at it and let me know. Now, we will include  the custom queries and the JPA readily available operations in the repository.

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java (hunk 23 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/DeviceController.java]: This controller will let the front end fetch all devices wheather they are set to encoder or decoder or not to anything. Assuming that when you first register an encoder or a decoder you have to first register it as a device and then assign it an encoder or a decoder

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java (hunk 21 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java]: why do you think that

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java (hunk 30 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: fixed

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java (hunk 11 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Decoder.java]: not sure about that, from my understanding serial numbers are unique. We can have multiple ports to a specific serial number

File: service/switchboardapp/pom.xml (hunk 17 above)
Comment (FGRCL) [reply service/switchboardapp/pom.xml:86]: I'm don't have any ideas of the top of my head, but maybe we could avoid issues like this by enforcing a CodeStyle file in IntelliJ for all the team. What do you think about it?

Comment (mohhef) [reply service/switchboardapp/pom.xml:86]: Thats a good idea, but i just found out we can install 'save actions' plugin and it will reformat the file, organize imports, etc.. on saving a file(intellij autosaves, might not be ideal to reformat in the middle of coding) or on pressing ctrl+shift+s. Ill try to do that on the pom.xml and see what happens

Comment (mohhef) [reply service/switchboardapp/pom.xml:86]: it fixed the issue! codestyle to enforce the styles is still good suggestion to enforce the styles

File: service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java (hunk 8 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/domain/Device.java]: Both should not have them, fixed.

File: service/switchboardapp/contracts/api-spec.yaml (hunk 14 above)
Comment (mohhef) [reply service/switchboardapp/contracts/api-spec.yaml:46]: i changed the ids  to match the method names we had, i also changed other stuff. I dont know the best conventions for the api-spec document( please advise if theres something wrong), however i made some changes so that it atleast matches our current code. I will implement it this pr if needed

**Comment by mohhef** [comment]
All comments have been addressed except enforcing the yaml script on the implementation, I suggest merging this PR and doing the enforce in the next PR

File: service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java (hunk 10 above)
Comment (mohhef) [reply service/switchboardapp/src/main/java/com/switchboard/app/controller/DecoderController.java]: fixed

File: service/switchboardapp/contracts/api-spec.yaml [hunk 35]
```diff
@@ -21,7 +53,7 @@ paths:
           content:
             application/json:
               schema:
-                $ref: '#/components/schemas/EncoderUuids'
+                $ref: '#/components/schemas/Encoder'
```
Comment (FGRCL) [inline service/switchboardapp/contracts/api-spec.yaml:56]: This model is inconsistent with the description of the endpoints. This model contains a single Encoder object while the endpoint should return a list of some kind. The reason I made it return a list of IDs is to reduce the amount of data in case there were a lot of encoders. But let's take care of that in the next PR

**Review by felixlapierre — APPROVED** [review]
Looks good to merge for now. We'll have to create tasks to represent the unfinished work of:
- Matching the controllers to the interfaces generated by the api spec
- Write unit and integration tests for this code

**Review by FGRCL — APPROVED** [review]
