### PR TITLE
[#28] Stream Creation Page

### LINKED ISSUE #28: Stream creation page
The user should be able to select a sender and a receiver, and indicate "start stream" or something similar. This will then make the appropriate call to the server to start the stream.

### LINKED ISSUE #109: Ripple effect from button click propagates to other buttons on device lists page
**Operating system:** 
 
 
* Windows 10
* Google Chrome

**Steps to reproduce:**
 
1. Run the frontend (npm start)
2. Click on either the Stream **or** the Add Device button.

**Expected result:**
 
* Ripple effect will stop at the end of the button you clicked.

**Actual result:**
 
* Ripple effect propagates to the other button.

**Visual proof:**
 
|  Actual  |
|:---------------:|
|  |

| Expected |
|:---------------:|
|  |

### PR DESCRIPTION
**Pull request by jun-loke**
# General info

**Issue number**: #28 

### Task description: 

- Created Streaming Page
- Streaming page is hooked up to backend

#### Additional changes
 

- Added Channels field to Device info
- Added Home page
- Added Routing to frontend, allowing different pages to exist
  - Include NavLink to make Breadcrumbs functional
- Make `Stream `and `Add Device` buttons into Components instead of just using styling
- Fixed #109 
 
 
| Original   | Updated|
|:---------------:|:---------------:|
| N/A | image|

# Testing

**Test coverage**:

# Additional notes

**Note to reviewers**:
- To navigate to the Streaming page, click `Streaming` on the home page
- The Stream button on the devices page also redirects to the Streaming page

**To do before merging**:
- [x] Waiting for #122 to be merged
- [x] Add Testing
  - All testing has been added as of 70fade9

### CODE REVIEW

File: frontend/src/General/DynamicBreadcrumb.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+export default class DynamicBreadcrumb extends React.Component {
+
+    render() {
+        var i = 0;
+        return (
+            <Box padding="2em 0em 0em 1em">
+                <Breadcrumbs aria-label="breadcrumb" id="breadcrumbParent">
+                    {this.props.breadcrumbs.map((crumb) => {
+                        return (
+                            <Link color="inherit" href={crumb[1]} id = {"breadcrumb"+i} key={"breadcrumb" + (i++)}>
```
Comment (mohhef) [inline frontend/src/General/DynamicBreadcrumb.js:18]: why not have the id of the component the same as href name, that way we dont need the i variable

Comment (mohhef) [inline frontend/src/General/DynamicBreadcrumb.js:18]: why not have the id of the component the same as href name, that way we dont need the i variable

File: frontend/src/index.js [hunk 2]
```diff
@@ -2,33 +2,34 @@ import React from 'react';
...
+    <BrowserRouter>
+      <HeaderBar />
+      <Switch>
+        <Route exact path={["/", "/Home"]} component={HomePage} />
+        <Route exact path="/Devices" 
+          render={(props) => (
+            <DeviceList {...props} dataSource={DeviceApi} />
+        )} />
+        <Route exact path="/Streaming" 
+        render={(props) => (
```
Comment (mohhef) [inline frontend/src/index.js]: i think you only need 'exact' on the home Route only

File: frontend/src/devicelist/DeviceList.js [hunk 3]
```diff
@@ -1,19 +1,24 @@
...
-    
+
     return (
         <Container>
-            <TitleBox />
-            <ContentsTable classes={styles} dataSource={props.dataSource}/>
+            <DynamicBreadcrumb breadcrumbs={[["Home", ""], ["My Devices", "Devices"]]} />
+            <Box padding="1em">
+                <TitleBox />
+                <ContentsTable classes={styles} dataSource={props.dataSource} />
```
Comment (mohhef) [inline frontend/src/devicelist/DeviceList.js]: This is for future reference:
I have used dataTables(https://datatables.net/) with plain js before and it makes alot of stuff in the tables easier for you. Like searching any column, ordering each coloumn, pagination, etc.... It gives you a lot of functionality.

I found this react library that seems to provide simllar functionality: https://www.npmjs.com/package/react-data-table-component#react-data-table-component

I imagine if we dont use a library for handling data to view in the table retrieved from the database, it could take a lot more time

File: frontend/src/createStream/StreamingPage.js [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+        return (
+            <Container>
+                <DynamicBreadcrumb
+                    breadcrumbs={[["Home", ""], ["My Devices", "Devices"], ["Streaming", "Streaming"]]} />
+                <Box padding="1em">
+                    <Box className="flexContents headerArea">
+                        <div className="title">Streaming</div>
+                    </Box>
+                    <div id="StreamingTable">
+
```
Comment (mohhef) [inline frontend/src/createStream/StreamingPage.js:27]: extra space here i think

File: frontend/src/createStream/StreamingTable.js [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+
+    handleSubmit(event) {
+
+        if (this.state.selectedReceiverID === "" || this.state.selectedSenderID === "") {
+            console.log("Please select a sender and a receiver");
+        }
+        else {
+            axios.post("http://localhost:8080/stream", {
+                inputChannelId: this.state.selectedSenderID,
+                outputChannelId: this.state.selectedReceiverID
```
Comment (mohhef) [inline frontend/src/createStream/StreamingTable.js]: can this be abstracted in a streamApi file?
Is this a new endpoint created by the new PR by francois?

**Review by mohhef — CHANGES_REQUESTED** [review]
I think it overall looks good, my only major suggestion we can discuss in a future meeting, is if using a library for creating the tables in our application could save us time.

I have a sample application that uses datatables, i can show it next meeting.

File: frontend/src/createStream/StreamingTable.js (hunk 5 above)
Comment (jun-loke) [reply frontend/src/createStream/StreamingTable.js]: Yeah, It's in anticipation for francois's PR 
I don't know much abt streamAPI files but I'll look into it

File: frontend/src/index.js (hunk 2 above)
Comment (jun-loke) [reply frontend/src/index.js]: For now you would be correct, However, but given the information on the mockups, it looks like the flow might be that you access the **Streaming** page through the **My Devices** page, thus the route might need to match the breadcrumb. In which case, it's better to set it as exact. Plus, if it turns out to be an issue, we can always remove it later

File: frontend/src/createStream/StreamingPage.js (hunk 4 above)
Comment (jun-loke) [reply frontend/src/createStream/StreamingPage.js:27]: Removed in 250a33c8

File: frontend/src/createStream/StreamingTable.js (hunk 5 above)
Comment (mohhef) [reply frontend/src/createStream/StreamingTable.js]: its just because i saw that you have the device requests in a file called DeviceApi, so maybe u can do something like that for stream endpoints

File: frontend/src/General/__tests__/HomePage.test.js [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+            , container);
+    })
+
+    var breadcrumbParent = document.getElementById("breadcrumbParent");
+    var children = breadcrumbParent.children.item(0).children;
+
+    expect(children.length).toBe(5);
+
+    expect(children[0].firstChild.firstChild.textContent).toBe("Home");
+    expect(children[0].firstChild.href).toBe("http://localhost/");
```
Comment (felixlapierre) [inline frontend/src/General/__tests__/HomePage.test.js:36]: This is just on sample data right? When we run the app in prod it won't link to localhost?

File: frontend/src/api/DeviceApi.js [hunk 7]
```diff
@@ -1,25 +1,27 @@
...
 
 export function getSenders(callback) {
-    axios("http://localhost:8080/encoder")
+    axios.get("http://localhost:8080/encoder")
         .then((senders) => {
             callback(
                 senders.data.map((sender) => {
-                    return new DeviceInfo("id", sender.device.displayName, sender.serialNumber, 0, "127.0.0.1", "2300", ["Sample sender"]);
-            }));
+                    return new DeviceInfo(sender.serialNumber, "Last Communication", "127.0.0.1", sender.device.displayName, 0, 0, [new OutChannelInfo(15, "channel 1", 420, null), new OutChannelInfo(65, "Channel 2", 490, null)], ["Sample sender"]);
```
Comment (felixlapierre) [inline frontend/src/api/DeviceApi.js]: We can get the IP address and channel info from the server response now right?

File: frontend/src/createStream/SelectDeviceTableRow.js [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+    ExpandMore
+} from '@material-ui/icons/';
+
+export default class SelectDeviceTableRow extends React.Component {
+
+    constructor(props) {
+        super(props)
+        this.state = {
+            deviceName: props.deviceDetails.name,
+            channels: props.deviceDetails.channels,
```
Comment (felixlapierre) [inline frontend/src/createStream/SelectDeviceTableRow.js]: Instead of copying `deviceName` and `channels` into the state, we can just refer to them directly with `this.props.deviceDetails.name` and `this.props.deviceDetails.channels` in the render method.

File: frontend/src/createStream/SelectDevicesTable.js [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+} from "@material-ui/core";
+
+import SearchBar from "../devicelist/SearchBar"
+import SelectDeviceTableRow from './SelectDeviceTableRow';
+
+export default class SelectDevicesTable extends React.Component {
+
+    constructor(props) {
+        super(props)
+        this.name = props.name;
```
Comment (felixlapierre) [inline frontend/src/createStream/SelectDevicesTable.js]: We can just refer to `props.name` directly in the render method through `this.props.name`

File: frontend/src/createStream/SelectDeviceTableRow.js [hunk 10]
```diff
@@ -0,0 +1,65 @@
...
+                            <ListItemText secondary="Select Channel" />
+                            <Select
+                                defaultValue=""
+                                onChange={this.props.onChange}>
+                                {
+                                    this.state.channels.map((channel) => {
+                                        return (
+                                            <MenuItem 
+                                            value={this.props.deviceIndex+"_"+ this.state.deviceName + "_" + channel.port} 
+                                            key={this.state.deviceName + "_" + channel.port}>
```
Comment (felixlapierre) [inline frontend/src/createStream/SelectDeviceTableRow.js]: You can use string interpolation here to make it a bit more readable.
```suggestion
                                            value={`${this.props.deviceIndex}_${this.state.deviceName}_${channel.port}`} 
                                            key={`${this.state.deviceName}_${channel.port}`}>
```

File: frontend/src/createStream/SelectDevicesTable.js [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+        var i = 0;
+        return (
+            <React.Fragment>
+                    <div className="subtitle">
+                        {this.name}
+                    </div>
+                    <SearchBar />
+                <div style={{ maxHeight: "300px", overflow: 'auto' }}>
+                    <List >
+                        {this.props.dataSource.map((device) => {
```
Comment (felixlapierre) [inline frontend/src/createStream/SelectDevicesTable.js]: Fun fact about map, the second parameter passed to your lambda is the index. So you can do
`this.props.dataSource.map((device, index) => {`
and you won't have to manage the i variable yourself!
(disclaimer: javascript still a terrible programming language)

File: frontend/src/createStream/StreamingTable.js (hunk 5 above)
Comment (felixlapierre) [reply frontend/src/createStream/StreamingTable.js]: Yeah we should move this to a file called StreamApi. I'd say it's not critical whether we do it here or not, we can do it in a later PR.

File: frontend/src/createStream/__tests__/StreamingPage.test.js [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+    expect(table.children.item(1).className).toBe("searchField");
+
+    expect(table.children.item(2)).not.toBe(null);
+    expect(list.childElementCount).toBe(9);
+    expect(list.firstChild).not.toBe(null);
+        
+})
+
+// Streaming Table
+test("Streaming Table has 2 tables as 1 button", () => {
```
Comment (felixlapierre) [inline frontend/src/createStream/__tests__/StreamingPage.test.js]: typo? 2 tables and 1 button

File: frontend/src/createStream/__tests__/StreamingTable.test.js [hunk 13]
```diff
@@ -0,0 +1,239 @@
...
+        return;
+    }
+
+}
+describe("<StreamingTable/>", () => {
+    let wrapper;
+
+    beforeEach(() => {
+
+        wrapper = Enzyme.shallow(<StreamingTable dataSource={new DummyData()} />)
```
Comment (felixlapierre) [inline frontend/src/createStream/__tests__/StreamingTable.test.js:33]: Why do we use Enzyme?

File: frontend/src/createStream/__tests__/StreamingTable.test.js [hunk 14]
```diff
@@ -0,0 +1,239 @@
...
+            axios.post.mockImplementationOnce(()=>Promise.reject(new Error(errorMessage)))
+
+            wrapper.instance().onSenderSelected(mockSender);            
+            wrapper.instance().onReceiverSelected(mockReceiver);
+
+            wrapper.instance().handleSubmit(new DummyData);
+
+            expect(axios.post).toHaveBeenCalledWith("http://localhost:8080/stream", expected);
+
+           // expect(console.log).toHaveBeenCalledWith("Error: " + errorMessage);
```
Comment (felixlapierre) [inline frontend/src/createStream/__tests__/StreamingTable.test.js]: Commented code

File: frontend/src/createStream/__tests__/StreamingTable.test.js [hunk 15]
```diff
@@ -0,0 +1,239 @@
...
+
+            const data =  {
+                data: "test"
+            }
+            axios.post.mockImplementationOnce(()=>Promise.resolve(data))
+
+            wrapper.instance().onSenderSelected(mockSender);            
+            wrapper.instance().onReceiverSelected(mockReceiver);
+
+            wrapper.instance().handleSubmit(new DummyData);
```
Comment (felixlapierre) [inline frontend/src/createStream/__tests__/StreamingTable.test.js]: don't we need a () for the constructor call? or does js let you do that?

File: frontend/src/createStream/__tests__/StreamingTable.test.js [hunk 16]
```diff
@@ -0,0 +1,239 @@
...
+
+            expect(axios.post).toHaveBeenCalledWith("http://localhost:8080/stream", expected);
+
+            setTimeout(
+                ()=>{
+                    expect(console.log).toHaveBeenCalledWith("Success. Stream Started.");
+                }
+                , 2000
+            )
```
Comment (felixlapierre) [inline frontend/src/createStream/__tests__/StreamingTable.test.js]: why do we need a timeout? are we waiting for render or something?

**Review by felixlapierre — COMMENTED** [review]
Only some minor questions and comments, lookin' real good :)

File: frontend/src/General/__tests__/HomePage.test.js (hunk 6 above)
Comment (jun-loke) [reply frontend/src/General/__tests__/HomePage.test.js:36]: I'm not too sure to be honest. This is just what worked for this test. This page is temporary anyways

File: frontend/src/api/DeviceApi.js (hunk 7 above)
Comment (jun-loke) [reply frontend/src/api/DeviceApi.js]: Waiting for frankie's PR before updating that. I didn't want to ask for things that aren't there

File: frontend/src/createStream/__tests__/StreamingTable.test.js (hunk 13 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js:33]: smart answer: Enzyme allows us to constrain the testing to the unit itself instead of indirectly testing children behaviours (Read more here: https://enzymejs.github.io/enzyme/docs/api/shallow.html )

Real answer: It was in every example I saw for testing states and I didn't think twice about it. Also it can read the state of something which is good because I'm not sure how to do that otherwise

File: frontend/src/createStream/__tests__/StreamingTable.test.js (hunk 15 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js]: Nope, it's not required. But I'll add it back anyways

File: frontend/src/createStream/__tests__/StreamingTable.test.js (hunk 16 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js]: Because it takes a bit before it calls the success message. 
As discussed, this is because this puts it at the back of the queue, letting the console.log to get called. Will reduce the timeout to 0

Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js]: Fixed in aee4deb

File: frontend/src/createStream/__tests__/StreamingTable.test.js (hunk 15 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js]: Fixed in aee4deb

File: frontend/src/createStream/__tests__/StreamingTable.test.js (hunk 14 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingTable.test.js]: Test removed in aee4deb as discussed

File: frontend/src/createStream/SelectDeviceTableRow.js (hunk 10 above)
Comment (jun-loke) [reply frontend/src/createStream/SelectDeviceTableRow.js]: Fixed: f1b9389e

File: frontend/src/createStream/SelectDevicesTable.js (hunk 11 above)
Comment (jun-loke) [reply frontend/src/createStream/SelectDevicesTable.js]: Fixed f1b9389e

File: frontend/src/createStream/__tests__/StreamingPage.test.js (hunk 12 above)
Comment (jun-loke) [reply frontend/src/createStream/__tests__/StreamingPage.test.js]: Fixed: f1b9389e

File: frontend/src/createStream/SelectDevicesTable.js (hunk 9 above)
Comment (jun-loke) [reply frontend/src/createStream/SelectDevicesTable.js]: Fixed f1b9389e

File: frontend/src/createStream/SelectDeviceTableRow.js (hunk 8 above)
Comment (jun-loke) [reply frontend/src/createStream/SelectDeviceTableRow.js]: Fixed: f1b9389e

**Comment by mohhef** [comment]
Is it possible to get these fixed before merging to master: https://sonarcloud.io/project/issues?id=bean-pod_switchboard&resolved=false&types=BUG

**Comment by jun-loke** [comment]
> Is it possible to get these fixed before merging to master: https://sonarcloud.io/project/issues?id=bean-pod_switchboard&resolved=false&types=BUG

@mohhef that code doesn't exist anymore

File: frontend/src/General/Buttons/StreamButton.js [hunk 17]
```diff
@@ -0,0 +1,41 @@
...
+} from '@material-ui/icons/';
+
+export default class StreamButton extends React.Component {
+    constructor(props) {
+        super(props);
+        this.id = props.id;
+    }
+    render() {
+
+        const StyledButton = withStyles({
```
Comment (gdzooks) [inline frontend/src/General/Buttons/StreamButton.js]: awkward empty lines placement

File: frontend/src/General/Buttons/AddDeviceButton.js [hunk 18]
```diff
@@ -0,0 +1,40 @@
...
+
+export default class AddDeviceButton extends React.Component {
+
+    constructor(props) {
+        super(props);
+        this.id = props.id;
+    }
+    render() {
+
+        const StyledButton = withStyles({
```
Comment (gdzooks) [inline frontend/src/General/Buttons/AddDeviceButton.js]: awkward empty line placement

**Review by mohhef — DISMISSED** [review]
Looks good to me.
To be discussed: using a library for the table on devices page

File: frontend/src/createStream/StreamingTable.js [hunk 19]
```diff
@@ -0,0 +1,124 @@
...
+                            <div className="streamingTable" id="ReceiverTable">
+                                <SelectDevicesTable
+                                    name="Receiver Devices"
+                                    dataSource={this.state.receivers}
+                                    onChange={this.onReceiverSelected.bind(this)} />
+                            </div>
+                        </Grid>
+                    </Grid>
+                </form>
+
```
Comment (gdzooks) [inline frontend/src/createStream/StreamingTable.js]: extra spaces on lines 95, 106, 119, and 122

**Review by felixlapierre — DISMISSED** [review]
Re-approving stale review

**Review by mohhef — DISMISSED** [review]

File: frontend/src/devicelist/DeviceListPage.js [hunk 20]
```diff
@@ -0,0 +1,40 @@
...
+} from "@material-ui/core"
+
+import TitleBox from './TitleBox'
+import ContentsTable from './ContentsTable'
+import DynamicBreadcrumb from '../General/DynamicBreadcrumb';
+
+export default class DeviceListPage extends React.Component {
+    constructor(props) {
+        super(props);
+
```
Comment (gdzooks) [inline frontend/src/devicelist/DeviceListPage.js]: empty line

File: frontend/src/devicelist/DeviceListPage.js [hunk 21]
```diff
@@ -0,0 +1,40 @@
...
+            <Container>
+                <DynamicBreadcrumb breadcrumbs={[["Home", ""], ["My Devices", "Devices"]]} />
+                <Box padding="1em">
+                    <TitleBox />
+                    <ContentsTable classes={this.useStyles} dataSource={this.props.dataSource} />
+                </Box>
+            </Container>
+        );
+    }
+
```
Comment (gdzooks) [inline frontend/src/devicelist/DeviceListPage.js]: empty linee

File: frontend/src/devicelist/DeviceListPage.js [hunk 22]
```diff
@@ -0,0 +1,40 @@
...
+        makeStyles((theme) => ({
+            root: {
+                backgroundColor: theme.palette.background.paper
+            },
+            tabs: {
+                borderRight: `1px solid ${theme.palette.divider}`,
+            },
+        }));
+    }
+    render() {
```
Comment (gdzooks) [inline frontend/src/devicelist/DeviceListPage.js]: insert empty line, actually

File: frontend/src/devicelist/HeadCells.js [hunk 23]
```diff
@@ -12,22 +12,35 @@ import HeadCell from '../model/HeadCell'
 export default class HeadCells extends React.Component {
     constructor(props) {
         super(props)
+        this.state = {
+            status:""
+        }
         this.headcells = this.getHeadCellData();
+
```
Comment (gdzooks) [inline frontend/src/devicelist/HeadCells.js]: empty line

File: frontend/src/devicelist/SearchBar.js [hunk 24]
```diff
@@ -39,11 +39,10 @@ export default class SearchBar extends React.Component {
     render() {
         return (
             <React.Fragment>
-                <div className={this.classes.search} class="searchField">
+                <div className={"searchField"}>
                     <TextField
                         placeholder="Search"
-                        InputProps={{ startAdornment: <InputAdornment position="start"> <Search /></InputAdornment> }}
-                        inputProps={{ 'aria-label': 'search' }}
+                        InputProps={{'aria-label': 'search', startAdornment: <InputAdornment position="start"> <Search /></InputAdornment> }}
```
Comment (gdzooks) [inline frontend/src/devicelist/SearchBar.js]: add a space after the `{{` to match end of line space

File: frontend/src/devicelist/SingleTableRow.js [hunk 25]
```diff
@@ -52,9 +48,10 @@ export default class SingleTableRow extends React.Component {
                     <TableCell class="chevronText lightestGrey" colSpan={7}>
                         <Collapse in={this.state.open} timeout="auto" unmountOnExit>
                             <Box margin={2}>
-                                <Typography variant="caption">
-                                    {this.rowExtras(this.props.row.extras)}
-                                </Typography>
+                                <Typography variant="h6">Channels</Typography>
+
```
Comment (gdzooks) [inline frontend/src/devicelist/SingleTableRow.js]: empty line

File: frontend/src/devicelist/SingleTableRow.js [hunk 26]
```diff
@@ -52,9 +48,10 @@ export default class SingleTableRow extends React.Component {
                     <TableCell class="chevronText lightestGrey" colSpan={7}>
                         <Collapse in={this.state.open} timeout="auto" unmountOnExit>
                             <Box margin={2}>
-                                <Typography variant="caption">
-                                    {this.rowExtras(this.props.row.extras)}
-                                </Typography>
+                                <Typography variant="h6">Channels</Typography>
```
Comment (gdzooks) [inline frontend/src/devicelist/SingleTableRow.js:51]: size of this feels a bit big but that can be discussed later :joy:

File: frontend/src/devicelist/ChannelDetailsTable.js [hunk 27]
```diff
@@ -0,0 +1,35 @@
...
+    TableBody,
+    TableCell,
+    TableRow
+} from "@material-ui/core";
+
+export default class ChannelDetailsTable extends React.Component {
+    constructor(props) {
+        super(props)
+    }
+    render() {
```
Comment (gdzooks) [inline frontend/src/devicelist/ChannelDetailsTable.js]: add an empty linee

File: frontend/src/devicelist/StatusIndicator.js [hunk 28]
```diff
@@ -1,22 +1,29 @@
...
+                return "green statusText";
+            case "Pending":
+                return "yellow statusText";
+            case "Error":
+                return "red statusText";
+            default:
+                return "lightGrey statusOfflineText";
+        }
+    }
+    render() {
```
Comment (gdzooks) [inline frontend/src/devicelist/StatusIndicator.js]: add separating empty line between methods

**Review by gdzooks — CHANGES_REQUESTED** [review]
requested changes are to do with empty lines and such.
great job!!

File: frontend/src/createStream/SelectDeviceTableRow.js [hunk 29]
```diff
@@ -0,0 +1,63 @@
...
+                            <ListItemText secondary="Select Channel" />
+                            <Select
+                                defaultValue=""
+                                onChange={this.props.onChange}>
+                                {
+                                    this.props.deviceDetails.channels.map((channel) => {
+                                        return (
+                                            <MenuItem
+                                                value={`${this.props.deviceIndex}_${this.props.deviceDetails.name}_${channel.id}`}
+                                                key={`${this.props.deviceDetails.name}_${channel.id}`} >
```
Comment (felixlapierre) [inline frontend/src/createStream/SelectDeviceTableRow.js]: Change `value` and `key` to just be `${channel.id}`, we don't need the other info and the channel ID is unique across all devices

Comment (jun-loke) [reply frontend/src/createStream/SelectDeviceTableRow.js]: 0c2fa9e

File: frontend/src/api/DeviceApi.js (hunk 7 above)
Comment (felixlapierre) [reply frontend/src/api/DeviceApi.js]: This is done now

**Review by felixlapierre — APPROVED** [review]
Re-approve

**Review by gdzooks — APPROVED** [review]
yum :+1:
