### PR TITLE
[#148] Fix All Bugs And Vulnerabilities, Fix 50% Code Smells

### LINKED ISSUE #148: Fix all sonarcloud bugs and vulnerabilities, fix 50% code smells
Acceptance critieria:
Sonarcloud indicates on master branch
- 0 bugs
- 0 vulnerabilities
- 220 or less code smells

### PR DESCRIPTION
**Pull request by ButlerJAL**
# General info

**Issue number**: closes #148 

**Task description**: 

Fixing smells one smell at a time to improve maintainability

# Testing

**Test coverage**: n/a

# Additional notes

**Note to reviewers**:
Review each commit individually. Commit messages with "review required" need special attention.

**To do before merging**: n/a

### CODE REVIEW

File: frontend/src/createStream/SelectDeviceTableRow.jsx [hunk 1]
```diff
@@ -52,3 +56,16 @@ export default class SelectDeviceTableRow extends React.Component {
...
+  deviceDetails: PropTypes.shape({
+    name: PropTypes.string,
+    channels: PropTypes.arrayOf(
+      PropTypes.shape({
+        id: PropTypes.number,
+        name: PropTypes.string,
+        port: PropTypes.number
+      })
+    )
+  }).isRequired,
```
Comment (jun-loke) [inline frontend/src/createStream/SelectDeviceTableRow.jsx]: Just use instanceOf(DeviceInfo)

File: frontend/src/devicelist/ChannelDetailsTable.jsx [hunk 2]
```diff
@@ -24,12 +28,19 @@ export default class ChannelDetailsTable extends React.Component {
...
       </Table>
     );
   }
 }
+ChannelDetailsTable.propTypes = {
+  channel: PropTypes.shape({
+    id: PropTypes.number,
+    name: PropTypes.string,
+    port: PropTypes.number
+  }).isRequired
```
Comment (jun-loke) [inline frontend/src/devicelist/ChannelDetailsTable.jsx]: Use instanceOf(ChannelInfo)

File: frontend/src/devicelist/DevicesTable.jsx [hunk 3]
```diff
@@ -44,3 +46,21 @@ export default class DevicesTable extends React.Component {
...
+      status: PropTypes.string,
+      ip: PropTypes.string,
+      channels: PropTypes.arrayOf(
+        PropTypes.shape({
+          id: PropTypes.number,
+          name: PropTypes.string,
+          port: PropTypes.number
+        })
+      )
+    })
```
Comment (jun-loke) [inline frontend/src/devicelist/DevicesTable.jsx]: `arrayOf(Proptypes.InstanceOf(DeviceInfo))`

File: frontend/src/devicelist/SingleTableRow.jsx [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+    serialNumber: PropTypes.string,
+    status: PropTypes.string,
+    ip: PropTypes.string,
+    channels: PropTypes.arrayOf(
+      PropTypes.shape({
+        id: PropTypes.number,
+        name: PropTypes.string,
+        port: PropTypes.number
+      })
+    )
```
Comment (jun-loke) [inline frontend/src/devicelist/SingleTableRow.jsx]: instanceOf(DeviceInfo)

File: frontend/src/devicelist/VerticalTabs.jsx [hunk 5]
```diff
@@ -19,14 +21,17 @@ export default class VerticalTabs extends React.Component {
...
     return (
       <>
         <Tabs
-          value={this.props.value}
+          value={value}
           onChange={this.handleChange}
           aria-label="Vertical tabs"
-          className={this.props.classes.tabs}
-          class="lightGrey blackFont flexContents"
+          className={`${tabs} lightGrey blackFont flexContents`}
```
Comment (jun-loke) [inline frontend/src/devicelist/VerticalTabs.jsx:34]: This is the CSS breaking change

File: frontend/src/streamlist/SingleStreamRow.jsx [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+    sender: PropTypes.shape({
+      name: PropTypes.string
+    }),
+    receiver: PropTypes.shape({
+      name: PropTypes.string
+    }),
+    status: PropTypes.string,
+    type: PropTypes.string,
+    time: PropTypes.string,
+    extras: PropTypes.arrayOf(PropTypes.string)
```
Comment (jun-loke) [inline frontend/src/streamlist/SingleStreamRow.jsx]: `Proptypes.instanceOf(StreamInfo)`

File: frontend/src/StatusIndicator.jsx [hunk 7]
```diff
@@ -15,10 +16,10 @@ export default class StatusIndicator extends React.Component {
...
-      <div className={this.getStatusStyle(this.props.status)}>
-        {this.props.status}
-      </div>
-    );
+    const { status } = this.props;
+    return <div className={this.getStatusStyle(status)}>{status}</div>;
   }
 }
+StatusIndicator.propTypes = {
+  status: PropTypes.string.isRequired
```
Comment (jun-loke) [inline frontend/src/StatusIndicator.jsx]: `PropTypes.oneOf(['Online', 'Offline', 'Error', 'Pending'])`

File: frontend/src/devicelist/SingleTableRow.jsx [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+            <StatusIndicator status={status} />
+          </TableCell>
+          <TableCell className="tableCell numeric">{ip}</TableCell>
+          <TableCell className="tableCell" align="center">
+            <ActionMenu />
+          </TableCell>
+        </TableRow>
+        <TableRow className="deviceDetails">
+          <TableCell className="chevronText lightestGrey" colSpan={7}>
+            <Collapse in={open} timeout="auto" unmountOnExit>
```
Comment (jun-loke) [inline frontend/src/devicelist/SingleTableRow.jsx:55]: Not quite sure what was changed here exactly. but from what I can see, not much. However, in terms of end result The CSS of the element seems to have changed a lot. with a lot of new properties that all seem to originate from actually using the mui table root class styling. This is more of a note for the cleanup PR but I tried

image
image

**Review by jun-loke — DISMISSED** [review]
Frontend seems fine, just some Proptype verifications that can be simplified.
Also, comments about the parts that break the CSS, though those can be left to be dealt with in a later PR, as dicussed

File: frontend/src/devicelist/VerticalTabs.jsx (hunk 5 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/VerticalTabs.jsx:34]: Yes, a review required note was added to the commit message regarding this change. Which do we keep? { tabs } or "lightGrey blackFont flexContents"?

File: frontend/src/devicelist/ChannelDetailsTable.jsx (hunk 2 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/ChannelDetailsTable.jsx]: There's no such thing as a ChannelInfo class in our project

Comment (ButlerJAL) [reply frontend/src/devicelist/ChannelDetailsTable.jsx]: This works however: `PropTypes.oneOfType([PropTypes.instanceOf(InputChannelInfo),PropTypes.instanceOf(OutputChannelInfo)]).isRequired`

File: frontend/src/createStream/SelectDeviceTableRow.jsx (hunk 1 above)
Comment (ButlerJAL) [reply frontend/src/createStream/SelectDeviceTableRow.jsx]: Great change request, done.

File: frontend/src/devicelist/ChannelDetailsTable.jsx (hunk 2 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/ChannelDetailsTable.jsx]: Done.

File: frontend/src/devicelist/DevicesTable.jsx (hunk 3 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/DevicesTable.jsx]: Great change request, done.

File: frontend/src/devicelist/SingleTableRow.jsx (hunk 4 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/SingleTableRow.jsx]: Great change request, done.

File: frontend/src/streamlist/SingleStreamRow.jsx (hunk 6 above)
Comment (ButlerJAL) [reply frontend/src/streamlist/SingleStreamRow.jsx]: Great change request, done.

File: frontend/src/StatusIndicator.jsx (hunk 7 above)
Comment (ButlerJAL) [reply frontend/src/StatusIndicator.jsx]: Great change request, done.

File: frontend/src/devicelist/SingleTableRow.jsx (hunk 8 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/SingleTableRow.jsx:55]: I changed the invalid DOM property 'class' to 'className'. My guess is that this changed the CSS class selector value of a TableCell component. Can we remove class/className property all together, or will that ruin the styling even more?

Comment (jun-loke) [reply frontend/src/devicelist/SingleTableRow.jsx:55]: not having the class at all removes all the styling, which isn't great It will require some investigation so, feel free to leave this for a later PR

File: frontend/src/devicelist/VerticalTabs.jsx (hunk 5 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/VerticalTabs.jsx:34]: For later PR

File: frontend/src/StatusIndicator.jsx [hunk 9]
```diff
@@ -1,4 +1,5 @@
 import React from "react";
+import PropTypes from "prop-types";
```
Comment (jun-loke) [inline frontend/src/StatusIndicator.jsx]: this should be in the `/general/` folder 
Also HeaderAppBar but I can't comment directly on that file

File: frontend/src/model/__tests__/ConvertDataFormat.test.js [hunk 10]
```diff
@@ -1,30 +1,39 @@
...
 const sampleLocalSender = new DeviceInfo(
   "test sender serial",
   null,
   "test sender ip",
   "test sender display",
   "offline",
-  sampleOutputChannels,
-  ["Additional Device Info goes here."]
+  undefined,
+  undefined
```
Comment (jun-loke) [inline frontend/src/model/__tests__/ConvertDataFormat.test.js:27]: Why are these not being assigned values anymore?
Also, if you're going to not set something, use null, not undefined. something should never be defined as undefined

File: frontend/src/model/ConvertDataFormat.js [hunk 11]
```diff
@@ -7,8 +7,7 @@ export function convertToDataObject(databaseDevice) {
     databaseDevice.device.ipAddress,
     databaseDevice.device.displayName,
     databaseDevice.device.status,
-    databaseDevice.inputs,
-    ["Additional Device Info goes here."]
```
Comment (jun-loke) [inline frontend/src/model/ConvertDataFormat.js:11]: We should still have an extras/notes section, but the database doesn't have that field yet.

**Review by jun-loke — COMMENTED** [review]
Just a couple small things that I saw for whichI don't quite understand the logic behind.

File: frontend/src/model/__tests__/ConvertDataFormat.test.js (hunk 10 above)
Comment (ButlerJAL) [reply frontend/src/model/__tests__/ConvertDataFormat.test.js:27]: The concern you pose is part of a greater issue that needs to be fixed in coordination with the backend in another PR. These fields do not match the data representation being sent between service and frontend, and I "labelled" them undefined to highlight this fact.

File: frontend/src/model/ConvertDataFormat.js (hunk 11 above)
Comment (ButlerJAL) [reply frontend/src/model/ConvertDataFormat.js:11]: The concern you pose is part of a greater issue that needs to be fixed in coordination with the backend in another PR. These fields do not match the data representation being sent between service and frontend, and I "labelled" them undefined to highlight this fact.

File: frontend/src/StatusIndicator.jsx (hunk 9 above)
Comment (ButlerJAL) [reply frontend/src/StatusIndicator.jsx]: Done.

**Comment by ButlerJAL** [comment]
@arejayelle,

Would you have any idea on how to mock the onChange property? I ask because in our StreamingPage.test.jsx we use two components, SelectDevicesTableRow and SelectDevicesTable, that require the onChange property for prop validation. I tried mocking onChange, but was unsuccessful.

The only side effect is a message that clutters our console.error log. The message states that the required onChange property is undefined when we run the tests. With that said, all tests pass, so, I don't think this is a major issue more so than it is annoying.

Below are the two tests that make use of, as mentioned above, a component requiring the onChange property:
```
// Select Devices Table row
test("Select Devices Table Row renders properly and Inner dropdown opens", () => {
  act(() => {
    render(
      <div id="testRow">
        <SelectDeviceTableRow deviceDetails={sampleSenders[0]} />
      </div>,
      container
    );
  });
  const testRow = document.getElementById("testRow");
  expect(testRow.childElementCount).toBe(1);
  expect(testRow.firstChild.textContent).toBe("Sender 1");

  const row = document.querySelector('[role="button"]');
  act(() => {
    ReactTestUtils.Simulate.click(row);
  });

  const collapse = document.getElementsByClassName(
    "MuiCollapse-container MuiCollapse-entered"
  );
  expect(collapse).not.toBe(null);
  const bean = document.getElementsByTagName("input");
  expect(bean).not.toBe(null);
});

```
```
// Select Devices Table
test("Select Devices Table renders with Title, search bar and List with SelectDeviceTable Rows", () => {
  act(() => {
    render(
      <BrowserRouter>
        <div id="testSelectTable">
          <SelectDevicesTable name="Test Table" dataSource={sampleSenders} />
        </div>
      </BrowserRouter>,
      container
    );
  });

  const table = document.getElementById("testSelectTable");

  expect(table.childElementCount).toBe(3);
  const list = table.lastChild.firstChild;

  expect(table.children.item(0).textContent).toBe("Test Table");
  expect(table.children.item(1).className).toBe("searchField");

  expect(table.children.item(2)).not.toBe(null);
  expect(list.childElementCount).toBe(9);
  expect(list.firstChild).not.toBe(null);
});
```

Let me know if you get any ideas. Else, I will just create a bug report for fixing in a future PR.

Thanks

**Comment by ButlerJAL** [comment]
Other than wanting to find a solution for my previous comment, this PR is ready to be merged subject to being approved by at least 2 reviewers.

All reported SonarCloud bugs and vulnerabilities have been fixed, and code smells have been drastically reduced above and beyond our target goal of 50% reduction.

File: frontend/src/createStream/SelectDeviceTableRow.jsx [hunk 12]
```diff
@@ -19,27 +21,30 @@ export default class SelectDeviceTableRow extends React.Component {
   }
 
   onClick() {
-    this.setState({ open: !this.state.open });
+    const { open } = this.state;
+    this.setState({ open: !open });
```
Comment (FGRCL) [inline frontend/src/createStream/SelectDeviceTableRow.jsx]: I think React recommends using the lambda form of `setState` when you need to access the `state` or `props` in your `setState`. [https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous)

File: frontend/src/createStream/StreamingTable.jsx [hunk 13]
```diff
@@ -43,6 +44,19 @@ export default class StreamingTable extends React.Component {
...
 
+  handleSubmit(event) {
+    const { selectedReceiverID, selectedSenderID } = this.state;
+    if (selectedReceiverID !== "" && selectedSenderID !== "") {
+      axios
+        .post("http://localhost:8080/stream", {
+          inputChannelId: selectedReceiverID,
+          outputChannelId: selectedSenderID
+        })
+        .then((response) => {});
```
Comment (FGRCL) [inline frontend/src/createStream/StreamingTable.jsx]: Is that promise even required anymore?

File: frontend/src/devicelist/__tests__/DeviceList.test.jsx [hunk 14]
```diff
@@ -119,11 +120,11 @@ function verifyStaticElements() {
 
   const streamButton = document.getElementById("DeviceListStreamBtn");
   expect(streamButton).not.toBe(null);
-  expect(streamButton.textContent).toBe(" Stream");
+  expect(streamButton.textContent).toBe("Stream");
 
   const addDeviceButton = document.getElementById("DeviceListAddDevBtn");
   expect(addDeviceButton).not.toBe(null);
-  expect(addDeviceButton.textContent).toBe(" Add Device");
+  expect(addDeviceButton.textContent).toBe("Add Device");
```
Comment (FGRCL) [inline frontend/src/devicelist/__tests__/DeviceList.test.jsx:127]: Shouldn't that make the tests fail?

**Review by FGRCL — DISMISSED** [review]
I didn't see any logic changes and only have 1 suggestion for improvement so you have my approval.

**Comment by felixlapierre** [comment]
> Would you have any idea on how to mock the onChange property? I ask because in our StreamingPage.test.jsx we use two components, SelectDevicesTableRow and SelectDevicesTable, that require the onChange property for prop validation. I tried mocking onChange, but was unsuccessful.

I've fixed this in f4759b8

**Comment by ButlerJAL** [comment]
> > Would you have any idea on how to mock the onChange property? I ask because in our StreamingPage.test.jsx we use two components, SelectDevicesTableRow and SelectDevicesTable, that require the onChange property for prop validation. I tried mocking onChange, but was unsuccessful.
> 
> I've fixed this in [f4759b8](https://github.com/bean-pod/switchboard/commit/f4759b8e75fea99a2f614db2c681f0419bc42df2)

Thank you!

File: frontend/src/devicelist/__tests__/DeviceList.test.jsx (hunk 14 above)
Comment (ButlerJAL) [reply frontend/src/devicelist/__tests__/DeviceList.test.jsx:127]: Why?

File: frontend/src/createStream/StreamingTable.jsx (hunk 13 above)
Comment (ButlerJAL) [reply frontend/src/createStream/StreamingTable.jsx]: Removed.

File: frontend/src/createStream/SelectDeviceTableRow.jsx (hunk 12 above)
Comment (ButlerJAL) [reply frontend/src/createStream/SelectDeviceTableRow.jsx]: Done.

File: frontend/src/devicelist/__tests__/DeviceList.test.jsx (hunk 14 above)
Comment (FGRCL) [reply frontend/src/devicelist/__tests__/DeviceList.test.jsx:127]: The expected text changed but I didn't see a similar change for actual text. Does `toBe()` ignore whitespaces?

**Review by FGRCL — APPROVED** [review]
Reapproving

File: frontend/src/model/ConvertDataFormat.js (hunk 11 above)
Comment (felixlapierre) [reply frontend/src/model/ConvertDataFormat.js:11]: Created issue #184 to reflect the problem with this ConvertDataFormat function and its tests.

**Comment by felixlapierre** [comment]
Created #185 to represent styling issues that arose from fixing the `class` vs `className` problem

**Review by felixlapierre — APPROVED** [review]
Looks good to me. Slight regression on the appearance of the frontend, but since we are reworking the table anyways, and the issues are only minor, we're good to create a bug issue and proceed. Thanks Joshua & good work!
